name: TestsAndAutogenOpenAPI

on:
  push:
    branches: [ main, develop ]
    paths: 
      - 'src/**'
      
jobs:
  test-and-docs:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout код
      uses: actions/checkout@v3
      with:
        token: ${{ secrets.GIT_TOKEN }}
    
    - name: Завантаження OpenAPI схеми
      run: |
        curl -o docs/api/openapi-generated.yaml http://16.170.148.253/api/schema/
    
    - name: Commit та push оновленої документації
      if: github.event_name == 'push'
      run: |
        git config --local user.email "github-actions[bot]@users.noreply.github.com"
        git config --local user.name "github-actions[bot]"
        git add docx/api/openapi-generated.yaml
        git diff --quiet && git diff --staged --quiet || (git commit -m "Автооновлення OpenAPI документації" && git push)
