name: Create Release

on:
  workflow_dispatch:
    inputs:
      version:
        description: 'Нова версія (i.e v0.3.9)'
        required: true
        type: string

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v1
        with:
          token: ${{secrets.GIT_TOKEN}}
          tag_name: ${{ github.event.inputs.version }}
          name: Release ${{ github.event.inputs.version }}
          generate_release_notes: true
