name: TestsAndAutogenOpenAPI

on:
  push:
    branches: [ main, develop ]
    paths: 
      - 'src/**'
      
jobs:
  test-and-docs:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout код
      uses: actions/checkout@v3
    
    - name: Налаштування Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'
    
    - name: Встановлення залежностей
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    
    - name: Запуск тестів
      run: |
        python manage.py test src.api.tests -v2
    
    - name: Завантаження OpenAPI схеми
      run: |
        curl -o docx/api/openapi-generated.yaml http://16.170.148.253/api/schema/
    
    - name: Commit та push оновленої документації
      if: github.event_name == 'push'
      run: |
        git config --local user.email "github-actions[bot]@users.noreply.github.com"
        git config --local user.name "github-actions[bot]"
        git add docx/api/openapi-generated.yaml
        git diff --quiet && git diff --staged --quiet || (git commit -m "Автооновлення OpenAPI документації" && git push)
